import Noliter from './Noliter';

export function createAnchor() { return new Noliter<HTMLAnchorElement>('a'); }
export function createAbbr() { return new Noliter('abbr'); }
export function createAddress() { return new Noliter('address'); }
export function createArea() { return new Noliter<HTMLAreaElement>('area'); }
export function createArticle() { return new Noliter('article'); }
export function createAside() { return new Noliter('aside'); }
export function createAudio() { return new Noliter<HTMLAudioElement>('audio'); }
export function createBold() { return new Noliter('b'); }
export function createBdi() { return new Noliter('bdi'); }
export function createBdo() { return new Noliter('bdo'); }
export function createBlockQuote() { return new Noliter<HTMLQuoteElement>('blockquote'); }
export function createBr() { return new Noliter<HTMLBRElement>('br'); }
export function createButton() { return new Noliter<HTMLButtonElement>('button'); }
export function createCanvas() { return new Noliter<HTMLCanvasElement>('canvas'); }
export function createCaption() { return new Noliter<HTMLTableCaptionElement>('caption'); }
export function createCite() { return new Noliter('cite'); }
export function createCode() { return new Noliter('code'); }
export function createCol() { return new Noliter<HTMLTableColElement>('col'); }
export function createColGroup() { return new Noliter<HTMLTableColElement>('colgroup'); }
export function createData() { return new Noliter<HTMLDataElement>('data'); }
export function createDataList() { return new Noliter<HTMLDataListElement>('datalist'); }
export function createDd() { return new Noliter('dd'); }
export function createDel() { return new Noliter<HTMLModElement>('del'); }
export function createDetails() { return new Noliter<HTMLDetailsElement>('details'); }
export function createDfn() { return new Noliter('dfn'); }
export function createDialog() { return new Noliter<HTMLDialogElement>('dialog'); }
export function createDiv() { return new Noliter<HTMLDivElement>('div'); }
export function createDl() { return new Noliter<HTMLDListElement>('dl'); }
export function createDt() { return new Noliter('dt'); }
export function createEm() { return new Noliter('em'); }
export function createEmbed() { return new Noliter<HTMLEmbedElement>('embed'); }
export function createFieldSet() { return new Noliter<HTMLFieldSetElement>('fieldset'); }
export function createFigCaption() { return new Noliter('figcaption'); }
export function createFigure() { return new Noliter('figure'); }
export function createFooter() { return new Noliter('footer'); }
export function createForm() { return new Noliter<HTMLFormElement>('form'); }
export function createH1() { return new Noliter<HTMLHeadingElement>('h1'); }
export function createH2() { return new Noliter<HTMLHeadingElement>('h2'); }
export function createH3() { return new Noliter<HTMLHeadingElement>('h3'); }
export function createH4() { return new Noliter<HTMLHeadingElement>('h4'); }
export function createH5() { return new Noliter<HTMLHeadingElement>('h5'); }
export function createH6() { return new Noliter<HTMLHeadingElement>('h6'); }
export function createHeader() { return new Noliter('header'); }
export function createHr() { return new Noliter<HTMLHRElement>('hr'); }
export function createItalic() { return new Noliter('i'); }
export function createIframe() { return new Noliter<HTMLIFrameElement>('iframe'); }
export function createImg() { return new Noliter<HTMLImageElement>('img'); }
export function createInput() { return new Noliter<HTMLInputElement>('input'); }
export function createIns() { return new Noliter<HTMLModElement>('ins'); }
export function createKbd() { return new Noliter('kbd'); }
export function createLabel() { return new Noliter<HTMLLabelElement>('label'); }
export function createLegend() { return new Noliter<HTMLLegendElement>('legend'); }
export function createLi() { return new Noliter<HTMLLIElement>('li'); }
export function createLink() { return new Noliter<HTMLLinkElement>('link'); }
export function createMain() { return new Noliter('main'); }
export function createMap() { return new Noliter<HTMLMapElement>('map'); }
export function createMark() { return new Noliter('mark'); }
export function createMeter() { return new Noliter<HTMLMeterElement>('meter'); }
export function createNav() { return new Noliter('nav'); }
export function createObject() { return new Noliter<HTMLObjectElement>('object'); }
export function createOl() { return new Noliter<HTMLOListElement>('ol'); }
export function createOptGroup() { return new Noliter<HTMLOptGroupElement>('optgroup'); }
export function createOption() { return new Noliter<HTMLOptionElement>('option'); }
export function createOutput() { return new Noliter<HTMLOutputElement>('output'); }
export function createParagraph() { return new Noliter<HTMLParagraphElement>('p'); }
export function createParam() { return new Noliter<HTMLParamElement>('param'); }
export function createPicture() { return new Noliter<HTMLPictureElement>('picture'); }
export function createPre() { return new Noliter<HTMLPreElement>('pre'); }
export function createProgress() { return new Noliter<HTMLProgressElement>('progress'); }
export function createQuote() { return new Noliter<HTMLQuoteElement>('q'); }
export function createSamp() { return new Noliter('samp'); }
export function createSection() { return new Noliter('section'); }
export function createSelect() { return new Noliter<HTMLSelectElement>('select'); }
export function createSmall() { return new Noliter('small'); }
export function createSource() { return new Noliter<HTMLSourceElement>('source'); }
export function createSpan() { return new Noliter<HTMLSpanElement>('span'); }
export function createStrong() { return new Noliter('strong'); }
export function createSub() { return new Noliter('sub'); }
export function createTextArea() { return new Noliter<HTMLTextAreaElement>('textarea'); }
export function createTable() { return new Noliter<HTMLTableElement>('table'); }
export function createThead() { return new Noliter<HTMLTableSectionElement>('thead'); }
export function createTbody() { return new Noliter<HTMLTableSectionElement>('tbody'); }
export function createTfoot() { return new Noliter<HTMLTableSectionElement>('tfoot'); }
export function createTh() { return new Noliter<HTMLTableHeaderCellElement>('th'); }
export function createTr() { return new Noliter<HTMLTableRowElement>('tr'); }
export function createTd() { return new Noliter<HTMLTableDataCellElement>('td'); }
export function createTime() { return new Noliter<HTMLTimeElement>('time'); }
export function createTrack() { return new Noliter<HTMLTrackElement>('track'); }
export function createUl() { return new Noliter<HTMLUListElement>('ul'); }
export function createVar() { return new Noliter('var'); }
