import {createElement} from './element';
import {setAttributes} from './attribute';
import {setProperties} from './property';
import {
  createAElement,
  createAbbrElement,
  createAddressElement,
  createAppletElement,
  createAreaElement,
  createArticleElement,
  createAsideElement,
  createAudioElement,
  createBElement,
  createBaseElement,
  createBaseFontElement,
  createBdiElement,
  createBdoElement,
  createBlockQuoteElement,
  createBodyElement,
  createBrElement,
  createButtonElement,
  createCanvasElement,
  createCaptionElement,
  createCiteElement,
  createCodeElement,
  createColElement,
  createColGroupElement,
  createDataElement,
  createDataListElement,
  createDdElement,
  createDelElement,
  createDetailsElement,
  createDfnElement,
  createDialogElement,
  createDirElement,
  createDivElement,
  createDlElement,
} from './html';

export {
  createElement,
  setAttributes,
  setProperties,
  createAElement,
  createAbbrElement,
  createAddressElement,
  createAppletElement,
  createAreaElement,
  createArticleElement,
  createAsideElement,
  createAudioElement,
  createBElement,
  createBaseElement,
  createBaseFontElement,
  createBdiElement,
  createBdoElement,
  createBlockQuoteElement,
  createBodyElement,
  createBrElement,
  createButtonElement,
  createCanvasElement,
  createCaptionElement,
  createCiteElement,
  createCodeElement,
  createColElement,
  createColGroupElement,
  createDataElement,
  createDataListElement,
  createDdElement,
  createDelElement,
  createDetailsElement,
  createDfnElement,
  createDialogElement,
  createDirElement,
  createDivElement,
  createDlElement,
};
