const {
  createAnchor,
  createAbbr,
  createAddress,
  createArea,
  createArticle,
  createAside,
  createAudio,
  createBold,
  createBdi,
  createBdo,
  createBlockQuote,
  createBr,
  createButton,
  createCanvas,
  createCaption,
  createCite,
  createCode,
  createCol,
  createColGroup,
  createData,
  createDataList,
  createDd,
  createDel,
  createDetails,
  createDfn,
  createDialog,
  createDiv,
  createDl,
  createDt,
  createEm,
  createEmbed,
  createFieldSet,
  createFigCaption,
  createFigure,
  createFooter,
  createForm,
  createH1,
  createH2,
  createH3,
  createH4,
  createH5,
  createH6,
  createHeader,
  createHr,
  createItalic,
  createIframe,
  createImg,
  createInput,
  createIns,
  createKbd,
  createLabel,
  createLegend,
  createLi,
  createLink,
  createMain,
  createMap,
  createMark,
  createMeter,
  createNav,
  createObject,
  createOl,
  createOptGroup,
  createOption,
  createOutput,
  createParagraph,
  createParam,
  createPicture,
  createPre,
  createProgress,
  createQuote,
  createSamp,
  createSection,
  createSelect,
  createSmall,
  createSource,
  createSpan,
  createStrong,
  createSub,
  createTextArea,
  createTable,
  createThead,
  createTbody,
  createTfoot,
  createTh,
  createTr,
  createTd,
  createTime,
  createTrack,
  createUl,
  createVar,
  createVideo,
} = require('../dist/index');

test('TagName comparison', () => {
  [
    { method: createAnchor, tagName: 'A' },
    { method: createAbbr, tagName: 'ABBR' },
    { method: createAddress, tagName: 'ADDRESS' },
    { method: createArea, tagName: 'AREA' },
    { method: createArticle, tagName: 'ARTICLE' },
    { method: createAside, tagName: 'ASIDE' },
    { method: createAudio, tagName: 'AUDIO' },
    { method: createBold, tagName: 'B' },
    { method: createBdi, tagName: 'BDI' },
    { method: createBdo, tagName: 'BDO' },
    { method: createBlockQuote, tagName: 'BLOCKQUOTE' },
    { method: createBr, tagName: 'BR' },
    { method: createButton, tagName: 'BUTTON' },
    { method: createCanvas, tagName: 'CANVAS' },
    { method: createCaption, tagName: 'CAPTION' },
    { method: createCite, tagName: 'CITE' },
    { method: createCode, tagName: 'CODE' },
    { method: createCol, tagName: 'COL' },
    { method: createColGroup, tagName: 'COLGROUP' },
    { method: createData, tagName: 'DATA' },
    { method: createDataList, tagName: 'DATALIST' },
    { method: createDd, tagName: 'DD' },
    { method: createDel, tagName: 'DEL' },
    { method: createDetails, tagName: 'DETAILS' },
    { method: createDfn, tagName: 'DFN' },
    { method: createDialog, tagName: 'DIALOG' },
    { method: createDiv, tagName: 'DIV' },
    { method: createDl, tagName: 'DL' },
    { method: createDt, tagName: 'DT' },
    { method: createEm, tagName: 'EM' },
    { method: createEmbed, tagName: 'EMBED' },
    { method: createFieldSet, tagName: 'FIELDSET' },
    { method: createFigCaption, tagName: 'FIGCAPTION' },
    { method: createFigure, tagName: 'FIGURE' },
    { method: createFooter, tagName: 'FOOTER' },
    { method: createForm, tagName: 'FORM' },
    { method: createH1, tagName: 'H1' },
    { method: createH2, tagName: 'H2' },
    { method: createH3, tagName: 'H3' },
    { method: createH4, tagName: 'H4' },
    { method: createH5, tagName: 'H5' },
    { method: createH6, tagName: 'H6' },
    { method: createHeader, tagName: 'HEADER' },
    { method: createHr, tagName: 'HR' },
    { method: createItalic, tagName: 'I' },
    { method: createIframe, tagName: 'IFRAME' },
    { method: createImg, tagName: 'IMG' },
    { method: createInput, tagName: 'INPUT' },
    { method: createIns, tagName: 'INS' },
    { method: createKbd, tagName: 'KBD' },
    { method: createLabel, tagName: 'LABEL' },
    { method: createLegend, tagName: 'LEGEND' },
    { method: createLi, tagName: 'LI' },
    { method: createLink, tagName: 'LINK' },
    { method: createMain, tagName: 'MAIN' },
    { method: createMap, tagName: 'MAP' },
    { method: createMark, tagName: 'MARK' },
    { method: createMeter, tagName: 'METER' },
    { method: createNav, tagName: 'NAV' },
    { method: createObject, tagName: 'OBJECT' },
    { method: createOl, tagName: 'OL' },
    { method: createOptGroup, tagName: 'OPTGROUP' },
    { method: createOption, tagName: 'OPTION' },
    { method: createOutput, tagName: 'OUTPUT' },
    { method: createParagraph, tagName: 'P' },
    { method: createParam, tagName: 'PARAM' },
    { method: createPicture, tagName: 'PICTURE' },
    { method: createPre, tagName: 'PRE' },
    { method: createProgress, tagName: 'PROGRESS' },
    { method: createQuote, tagName: 'Q' },
    { method: createSamp, tagName: 'SAMP' },
    { method: createSection, tagName: 'SECTION' },
    { method: createSelect, tagName: 'SELECT' },
    { method: createSmall, tagName: 'SMALL' },
    { method: createSource, tagName: 'SOURCE' },
    { method: createSpan, tagName: 'SPAN' },
    { method: createStrong, tagName: 'STRONG' },
    { method: createSub, tagName: 'SUB' },
    { method: createTextArea, tagName: 'TEXTAREA' },
    { method: createTable, tagName: 'TABLE' },
    { method: createThead, tagName: 'THEAD' },
    { method: createTbody, tagName: 'TBODY' },
    { method: createTfoot, tagName: 'TFOOT' },
    { method: createTh, tagName: 'TH' },
    { method: createTr, tagName: 'TR' },
    { method: createTd, tagName: 'TD' },
    { method: createTime, tagName: 'TIME' },
    { method: createTrack, tagName: 'TRACK' },
    { method: createUl, tagName: 'UL' },
    { method: createVar, tagName: 'VAR' },
    { method: createVideo, tagName: 'VIDEO' },
  ].forEach(({ method, tagName }) => {
    expect(
      method()
        .dom
        .tagName
    ).toBe(tagName);
  });
});
