const {
  createAnchorElement,
  createAbbrElement,
  createAddressElement,
  createAppletElement,
  createAreaElement,
  createArticleElement,
  createAsideElement,
  createAudioElement,
  createBoldElement,
  createBaseElement,
  createBaseFontElement,
  createBdiElement,
  createBdoElement,
  createBlockQuoteElement,
  createBodyElement,
  createBrElement,
  createButtonElement,
  createCanvasElement,
  createCaptionElement,
  createCiteElement,
  createCodeElement,
  createColElement,
  createColGroupElement,
  createDataElement,
  createDataListElement,
  createDdElement,
  createDelElement,
  createDetailsElement,
  createDfnElement,
  createDialogElement,
  createDirElement,
  createDivElement,
  createDlElement,
  createDtElement,
  createEmElement,
  createEmbedElement,
  createFieldSetElement,
  createFigcaptionElement,
  createFigureElement,
  createFontElement,
  createFooterElement,
  createFormElement,
  createFrameElement,
  createFrameSetElement,
  createH1Element,
  createH2Element,
  createH3Element,
  createH4Element,
  createH5Element,
  createH6Element,
  createHeadElement,
  createHeaderElement,
  createHGroupElement,
  createHrElement,
  createHtmlElement,
} = require('../dist/index');

test('HTMLElement creation test', () => {
  expect(createAnchorElement().tagName).toBe('A');
  expect(createAbbrElement().tagName).toBe('ABBR');
  expect(createAddressElement().tagName).toBe('ADDRESS');
  expect(createAppletElement().tagName).toBe('APPLET');
  expect(createAreaElement().tagName).toBe('AREA');
  expect(createArticleElement().tagName).toBe('ARTICLE');
  expect(createAsideElement().tagName).toBe('ASIDE');
  expect(createAudioElement().tagName).toBe('AUDIO');
  expect(createBoldElement().tagName).toBe('B');
  expect(createBaseElement().tagName).toBe('BASE');
  expect(createBaseFontElement().tagName).toBe('BASEFONT');
  expect(createBdiElement().tagName).toBe('BDI');
  expect(createBdoElement().tagName).toBe('BDO');
  expect(createBlockQuoteElement().tagName).toBe('BLOCKQUOTE');
  expect(createBodyElement().tagName).toBe('BODY');
  expect(createBrElement().tagName).toBe('BR');
  expect(createButtonElement().tagName).toBe('BUTTON');
  expect(createCanvasElement().tagName).toBe('CANVAS');
  expect(createCaptionElement().tagName).toBe('CAPTION');
  expect(createCiteElement().tagName).toBe('CITE');
  expect(createCodeElement().tagName).toBe('CODE');
  expect(createColElement().tagName).toBe('COL');
  expect(createColGroupElement().tagName).toBe('COLGROUP');
  expect(createDataElement().tagName).toBe('DATA');
  expect(createDataListElement().tagName).toBe('DATALIST');
  expect(createDdElement().tagName).toBe('DD');
  expect(createDelElement().tagName).toBe('DEL');
  expect(createDetailsElement().tagName).toBe('DETAILS');
  expect(createDfnElement().tagName).toBe('DFN');
  expect(createDialogElement().tagName).toBe('DIALOG');
  expect(createDirElement().tagName).toBe('DIR');
  expect(createDivElement().tagName).toBe('DIV');
  expect(createDlElement().tagName).toBe('DL');
  expect(createDtElement().tagName).toBe('DT');
  expect(createEmElement().tagName).toBe('EM');
  expect(createEmbedElement().tagName).toBe('EMBED');
  expect(createFieldSetElement().tagName).toBe('FIELDSET');
  expect(createFigcaptionElement().tagName).toBe('FIGCAPTION');
  expect(createFigureElement().tagName).toBe('FIGURE');
  expect(createFontElement().tagName).toBe('FONT');
  expect(createFooterElement().tagName).toBe('FOOTER');
  expect(createFormElement().tagName).toBe('FORM');
  expect(createFrameElement().tagName).toBe('FRAME');
  expect(createFrameSetElement().tagName).toBe('FRAMESET');
  expect(createH1Element().tagName).toBe('H1');
  expect(createH2Element().tagName).toBe('H2');
  expect(createH3Element().tagName).toBe('H3');
  expect(createH4Element().tagName).toBe('H4');
  expect(createH5Element().tagName).toBe('H5');
  expect(createH6Element().tagName).toBe('H6');
  expect(createHeadElement().tagName).toBe('HEAD');
  expect(createHeaderElement().tagName).toBe('HEADER');
  expect(createHGroupElement().tagName).toBe('HGROUP');
  expect(createHrElement().tagName).toBe('HR');
  expect(createHtmlElement().tagName).toBe('HTML');
});
