const {
  createAnchor,
  createAbbr,
  createAddress,
  createApplet,
  createArea,
  createArticle,
  createAside,
  createAudio,
  createBold,
  createBase,
  createBaseFont,
  createBdi,
  createBdo,
  createBlockQuote,
  createBody,
  createBr,
  createButton,
  createCanvas,
  createCaption,
  createCite,
  createCode,
  createCol,
  createColGroup,
  createData,
  createDataList,
  createDd,
  createDel,
  createDetails,
  createDfn,
  createDialog,
  createDir,
  createDiv,
  createDl,
  createDt,
  createHeader,
  createLink,
  createMain,
  createSection,
  createSpan,
} = require("../dist/index");

test("create html", () => {
  expect(createAnchor().tagName).toBe("A");
  expect(createAbbr().tagName).toBe("ABBR");
  expect(createAddress().tagName).toBe("ADDRESS");
  expect(createApplet().tagName).toBe("APPLET");
  expect(createArea().tagName).toBe("AREA");
  expect(createArticle().tagName).toBe("ARTICLE");
  expect(createAside().tagName).toBe("ASIDE");
  expect(createAudio().tagName).toBe("AUDIO");
  expect(createBold().tagName).toBe("B");
  expect(createBase().tagName).toBe("BASE");
  expect(createBaseFont().tagName).toBe("BASEFONT");
  expect(createBdi().tagName).toBe("BDI");
  expect(createBdo().tagName).toBe("BDO");
  expect(createBlockQuote().tagName).toBe("BLOCKQUOTE");
  expect(createBody().tagName).toBe("BODY");
  expect(createBr().tagName).toBe("BR");
  expect(createButton().tagName).toBe("BUTTON");
  expect(createCanvas().tagName).toBe("CANVAS");
  expect(createCaption().tagName).toBe("CAPTION");
  expect(createCite().tagName).toBe("CITE");
  expect(createCode().tagName).toBe("CODE");
  expect(createCol().tagName).toBe("COL");
  expect(createColGroup().tagName).toBe("COLGROUP");
  expect(createData().tagName).toBe("DATA");
  expect(createDataList().tagName).toBe("DATALIST");
  expect(createDd().tagName).toBe("DD");
  expect(createDel().tagName).toBe("DEL");
  expect(createDetails().tagName).toBe("DETAILS");
  expect(createDfn().tagName).toBe("DFN");
  expect(createDialog().tagName).toBe("DIALOG");
  expect(createDir().tagName).toBe("DIR");
  expect(createDiv().tagName).toBe("DIV");
  expect(createDl().tagName).toBe("DL");
  expect(createDt().tagName).toBe("DT");
});
